import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const localeOptions = [['en', 'English'], ['zh', '中文']];
const copy = {
  en: { language: 'Language', collections: 'Collections', livingMuseum: 'A living museum', halls: 'Halls', friendshipArchive: 'Friendship Archive', languageGallery: 'Language Gallery', starObservatory: 'Star Observatory', listeningRoom: 'Listening Room', privateHouse: 'My Private House', friendshipArchives: 'My Friendship Archives', tellStory: 'Tell us your story', beginStory: 'Begin your friendship story', close: 'Close ×', glowing: 'glowing', resting: 'resting', privateForTwo: '🔒 Just for the two of you', landingEyebrow: 'A LIVING COLLECTION', landingTitle: 'Girlie Friendship Museum.', landingBody: 'A garden museum keeping girls’ friendship stories from around the world — and making room for your own.', exploreGirls: 'Explore the girls', archiveEyebrow: 'FIRST GALLERY · FRIENDSHIP ARCHIVE', archiveTitle: 'Every friendship leaves a trace.', archiveBody: 'Walk slowly. Each flower is an entry in the collection, holding a city, a word, and a story.', beginVisiting: 'Begin visiting', scrollArchive: 'Friendship Archive · Gallery one', scrollPrompt: 'Scroll gently to meet the girls, one story at a time', endingEyebrow: 'A LIVING MUSEUM', endingTitle: 'More friendship stories are always finding their way here.', endingBody: 'What will you remember? Every girl has a story; every friendship has a memory that deserves a place to stay.' },
  zh: { language: '语言', collections: '馆藏', livingMuseum: '会生长的博物馆', halls: '展厅', friendshipArchive: '友谊档案', languageGallery: '语言展厅', starObservatory: '星空观测室', listeningRoom: '聆听室', privateHouse: '我的闺蜜小屋', friendshipArchives: '我的友谊档案', tellStory: '讲讲你们的故事', beginStory: '开始记录你们的故事', close: '关闭 ×', glowing: '正在发光', resting: '正在沉睡', privateForTwo: '🔒 只属于你们两人', landingEyebrow: '会生长的馆藏', landingTitle: 'Girlie 友谊博物馆。', landingBody: '一座收藏世界各地女孩友谊故事的花园博物馆，也为你的故事留出位置。', exploreGirls: '探索女孩们', archiveEyebrow: '第一展厅 · 友谊档案', archiveTitle: '每一段友谊都会留下痕迹。', archiveBody: '慢慢走。每朵花都是一件馆藏，保存着一座城市、一个词语和一个故事。', beginVisiting: '开始参观', scrollArchive: '友谊档案 · 第一展厅', scrollPrompt: '轻轻向后滚动，依次遇见女孩们的故事', endingEyebrow: '会生长的博物馆', endingTitle: '更多友谊故事正不断来到这里。', endingBody: '你会记住什么？每个女孩都有故事，每段友谊都有值得留下的记忆。' },
};
Object.assign(copy.en, { buildSecretHouse: 'Build a Secret House', interviewCollection: 'Private collection · 01', friendshipInterview: 'AI Friendship Interview', saveClose: 'Save & close', archivistConversation: 'A conversation with the friendship archivist', interviewTitle: 'Tell us about someone who changed your life.', interviewBody: 'There is no form to complete. Share only what feels right; the unwritten parts can stay yours.', archivist: 'The archivist', you: 'You', memoriesGathered: '{count} {unit} gathered', memory: 'memory', memories: 'memories', becomingArchive: 'She’s becoming part of your archive →', writeAnything: 'Write as much or as little as you want…', leaveUnwritten: 'Leave this part unwritten', continue: 'Continue', skip: 'I’d rather leave that part unwritten.', firstQuestion: 'Let’s start somewhere easy. When did you first meet her?', localArchiveReady: 'I can already feel the shape of this friendship. When you’re ready, we can turn these memories into your private archive — nothing is public unless you decide it should be.' });
Object.assign(copy.zh, { buildSecretHouse: '建造一间秘密小屋', interviewCollection: '私密馆藏 · 01', friendshipInterview: 'AI 友谊访谈', saveClose: '保存并关闭', archivistConversation: '与友谊档案师的对话', interviewTitle: '和我们聊聊那个改变你生命的人。', interviewBody: '这里没有需要填完的表格。只分享你愿意分享的部分；没有写下的内容也可以留给你自己。', archivist: '档案师', you: '你', memoriesGathered: '已收集 {count} 个{unit}', memory: '记忆', memories: '记忆', becomingArchive: '她正在成为你的馆藏 →', writeAnything: '想写多少都可以…', leaveUnwritten: '这部分暂时不写', continue: '继续', skip: '这部分我想暂时不写。', firstQuestion: '我们从一个简单的地方开始吧。你们第一次见面是什么时候？', localArchiveReady: '我已经能感到这段友谊的轮廓了。准备好时，我们可以把这些记忆整理进你的私密档案——除非你决定分享，否则没有任何内容会公开。' });
const LocaleContext = createContext(null);
const key = 'girlie_locale';
const format = (value, variables = {}) => String(value).replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? '');

export function LocaleProvider({ children }) {
  const [locale, setLocaleState] = useState(() => { try { return localStorage.getItem(key) === 'zh' ? 'zh' : 'en'; } catch { return 'en'; } });
  const setLocale = (next) => { if (!copy[next]) return; setLocaleState(next); try { localStorage.setItem(key, next); } catch {} };
  useEffect(() => { document.documentElement.lang = locale === 'zh' ? 'zh-CN' : 'en'; }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (name, variables) => format(copy[locale][name] ?? copy.en[name] ?? name, variables) }), [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}
export function useLocale() { const value = useContext(LocaleContext); if (!value) throw new Error('LocaleProvider is required'); return value; }
export function LocaleMenu({ className = '' }) { const { locale, setLocale, t } = useLocale(); return <label className={`locale-menu ${className}`}><span className="sr-only">{t('language')}</span><select aria-label={t('language')} value={locale} onChange={(event) => setLocale(event.target.value)}><option value="en">English</option><option value="zh">中文</option></select></label>; }
