import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export const localeOptions = [['en', 'English'], ['zh', '中文']];
const copy = {
  en: { language: 'Language', collections: 'Collections', livingMuseum: 'A living museum', halls: 'Halls', friendshipArchive: 'Friendship Archive', languageGallery: 'Language Gallery', starObservatory: 'Star Observatory', listeningRoom: 'Listening Room', privateHouse: 'My Private House', friendshipArchives: 'My Friendship Archives', tellStory: 'Tell us your story', beginStory: 'Begin your friendship story', close: 'Close ×', glowing: 'glowing', resting: 'resting', privateForTwo: '🔒 Just for the two of you', landingEyebrow: 'A LIVING COLLECTION', landingTitle: 'Girlie Friendship Museum.', landingBody: 'A garden museum keeping girls’ friendship stories from around the world — and making room for your own.', exploreGirls: 'Explore the girls', archiveEyebrow: 'FIRST GALLERY · FRIENDSHIP ARCHIVE', archiveTitle: 'Every friendship leaves a trace.', archiveBody: 'Walk slowly. Each flower is an entry in the collection, holding a city, a word, and a story.', beginVisiting: 'Begin visiting', scrollArchive: 'Friendship Archive · Gallery one', scrollPrompt: 'Scroll gently to meet the girls, one story at a time', endingEyebrow: 'A LIVING MUSEUM', endingTitle: 'More friendship stories are always finding their way here.', endingBody: 'What will you remember? Every girl has a story; every friendship has a memory that deserves a place to stay.' },
  zh: { language: '语言', collections: '馆藏', livingMuseum: '会生长的博物馆', halls: '展厅', friendshipArchive: '友谊档案', languageGallery: '语言展厅', starObservatory: '星空观测室', listeningRoom: '聆听室', privateHouse: '我的闺蜜小屋', friendshipArchives: '我的友谊档案', tellStory: '讲讲你们的故事', beginStory: '开始记录你们的故事', close: '关闭 ×', glowing: '正在发光', resting: '正在沉睡', privateForTwo: '🔒 只属于你们两人', landingEyebrow: '会生长的馆藏', landingTitle: 'Girlie 友谊博物馆。', landingBody: '一座收藏世界各地女孩友谊故事的花园博物馆，也为你的故事留出位置。', exploreGirls: '探索女孩们', archiveEyebrow: '第一展厅 · 友谊档案', archiveTitle: '每一段友谊都会留下痕迹。', archiveBody: '慢慢走。每朵花都是一件馆藏，保存着一座城市、一个词语和一个故事。', beginVisiting: '开始参观', scrollArchive: '友谊档案 · 第一展厅', scrollPrompt: '轻轻向后滚动，依次遇见女孩们的故事', endingEyebrow: '会生长的博物馆', endingTitle: '更多友谊故事正不断来到这里。', endingBody: '你会记住什么？每个女孩都有故事，每段友谊都有值得留下的记忆。' },
};
Object.assign(copy.en, { buildSecretHouse: 'Build a Secret House', interviewCollection: 'Private collection · 01', friendshipInterview: 'AI Friendship Interview', saveClose: 'Save & close', archivistConversation: 'A conversation with the friendship archivist', interviewTitle: 'Tell us about someone who changed your life.', interviewBody: 'There is no form to complete. Share only what feels right; the unwritten parts can stay yours.', archivist: 'The archivist', you: 'You', memoriesGathered: '{count} {unit} gathered', memory: 'memory', memories: 'memories', becomingArchive: 'She’s becoming part of your archive →', writeAnything: 'Write as much or as little as you want…', leaveUnwritten: 'Leave this part unwritten', continue: 'Continue', skip: 'I’d rather leave that part unwritten.', firstQuestion: 'Let’s start somewhere easy. When did you first meet her?', localArchiveReady: 'I can already feel the shape of this friendship. When you’re ready, we can turn these memories into your private archive — nothing is public unless you decide it should be.' });
Object.assign(copy.zh, { buildSecretHouse: '建造一间秘密小屋', interviewCollection: '私密馆藏 · 01', friendshipInterview: 'AI 友谊访谈', saveClose: '保存并关闭', archivistConversation: '与友谊档案师的对话', interviewTitle: '和我们聊聊那个改变你生命的人。', interviewBody: '这里没有需要填完的表格。只分享你愿意分享的部分；没有写下的内容也可以留给你自己。', archivist: '档案师', you: '你', memoriesGathered: '已收集 {count} 个{unit}', memory: '记忆', memories: '记忆', becomingArchive: '她正在成为你的馆藏 →', writeAnything: '想写多少都可以…', leaveUnwritten: '这部分暂时不写', continue: '继续', skip: '这部分我想暂时不写。', firstQuestion: '我们从一个简单的地方开始吧。你们第一次见面是什么时候？', localArchiveReady: '我已经能感到这段友谊的轮廓了。准备好时，我们可以把这些记忆整理进你的私密档案——除非你决定分享，否则没有任何内容会公开。' });
Object.assign(copy.en, { authPrivate: 'Private room', authTitle: 'Begin by keeping it yours.', authBody: 'Create an account to begin your private friendship interview. Your words, memories, and archive stay linked to you.', yourName: 'Your name', email: 'Email', password: 'Password (6+ characters)', createPrivate: 'Create my private room', enterPrivate: 'Enter my private room', accountExists: 'I already have an account', createInstead: 'Create an account instead', checkEmail: 'Check your email to confirm your private room.', welcomeBack: 'Welcome back to your room.', archiveBack: '← My room', privateArchive: 'Private Friendship Archive', locked: 'locked', sharedPermission: 'shared by permission', doneEditing: 'Done editing', editArchive: 'Edit archive', addMemory: '＋ Add a memory', myArchive: 'My Friendship Archive', forFriend: 'For {name}', takingShape: 'A friendship still taking shape', privateDefault: 'private by default', ourStory: 'Our Story', timeline: 'Friendship Timeline', undated: 'Undated', firstDate: 'The first date can arrive whenever you remember it.', importantPlaces: 'Important Places', placesEmpty: 'A school gate, a bakery, a city far away — add them through a memory.', friendshipObjects: 'Friendship Objects', objectsEmpty: 'When an object appears in your story, the archivist will place it here.', object: 'Object', keywords: 'Keywords', wordsWaiting: 'waiting for the words that belong to you', herSentence: 'Her Sentence', sentenceWaiting: 'The strongest sentence is still on its way.', timeCapsule: 'Time Capsule', openIn: 'Open in {value}', capsuleBody: 'Keep a letter, a voice note, or one small hope for later.', privateArchives: 'My Friendship Archives', shelfTitle: 'A shelf for the friendships that are yours.', signOut: 'Sign out', signInForever: 'Sign in to keep forever', roomProtected: 'Your room is protected by access rules and visible only to your account.', accountBefore: 'Create an account before beginning an interview, so every memory can remain safely yours.', myFriendships: 'My Friendships', archives: 'archives', archive: 'archive', savedPrivately: 'saved privately', accountRequired: 'account required', friendshipProgress: 'A friendship in progress', firstShelf: 'The first shelf is waiting.', shelfBody: 'Begin with one person, one memory, or one ordinary thing that still reminds you of her.' });
Object.assign(copy.zh, { authPrivate: '私密小屋', authTitle: '先把它留给你自己。', authBody: '创建账号后开始私密友谊访谈。你的话语、记忆与档案都会和你绑定。', yourName: '你的名字', email: '邮箱', password: '密码（至少 6 位）', createPrivate: '创建我的闺蜜小屋', enterPrivate: '进入我的闺蜜小屋', accountExists: '我已经有账号', createInstead: '改为创建账号', checkEmail: '请查看邮箱，确认你的私密小屋。', welcomeBack: '欢迎回到你的小屋。', archiveBack: '← 我的小屋', privateArchive: '私密友谊档案', locked: '已锁定', sharedPermission: '经允许分享', doneEditing: '完成编辑', editArchive: '编辑档案', addMemory: '＋ 添加一段记忆', myArchive: '我的友谊档案', forFriend: '献给 {name}', takingShape: '一段仍在成形的友谊', privateDefault: '默认私密', ourStory: '我们的故事', timeline: '友谊时间线', undated: '未标日期', firstDate: '第一天会在你想起时来到。', importantPlaces: '重要地点', placesEmpty: '学校门口、面包店或遥远的城市——在一段记忆里把它们加进来。', friendshipObjects: '友谊物件', objectsEmpty: '当一个物件出现在故事中，档案师会把它放在这里。', object: '物件', keywords: '关键词', wordsWaiting: '等待属于你们的词语', herSentence: '她的一句话', sentenceWaiting: '最有力量的一句话还在路上。', timeCapsule: '时间胶囊', openIn: '{value} 后开启', capsuleBody: '留下一封信、一段语音，或一个给未来的小小愿望。', privateArchives: '我的友谊档案', shelfTitle: '一层只属于你自己的友谊书架。', signOut: '退出登录', signInForever: '登录以永久保存', roomProtected: '你的小屋受访问规则保护，只对你的账号可见。', accountBefore: '先创建账号再开始访谈，让每段记忆都安全地留在你身边。', myFriendships: '我的友谊', archives: '份档案', archive: '份档案', savedPrivately: '已私密保存', accountRequired: '需要账号', friendshipProgress: '一段正在展开的友谊', firstShelf: '第一层书架正在等待。', shelfBody: '从一个人、一段记忆，或一件仍会让你想起她的平常小事开始。' });
const LocaleContext = createContext(null);
const key = 'girlie_locale';
const format = (value, variables = {}) => String(value).replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? '');

export function LocaleProvider({ children }) {
  const [locale, setLocaleState] = useState(() => { try { return localStorage.getItem(key) === 'zh' ? 'zh' : 'en'; } catch { return 'en'; } });
  const setLocale = (next) => { if (!copy[next]) return; setLocaleState(next); try { localStorage.setItem(key, next); } catch {} };
  useEffect(() => { document.documentElement.lang = locale === 'zh' ? 'zh-CN' : 'en'; }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (name, variables) => format(copy[locale][name] ?? copy.en[name] ?? name, variables) }), [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}
export function useLocale() { const value = useContext(LocaleContext); if (!value) throw new Error('LocaleProvider is required'); return value; }
export function LocaleMenu({ className = '' }) { const { locale, setLocale, t } = useLocale(); return <label className={`locale-menu ${className}`}><span className="sr-only">{t('language')}</span><select aria-label={t('language')} value={locale} onChange={(event) => setLocale(event.target.value)}><option value="en">English</option><option value="zh">中文</option></select></label>; }
